# Generated by Django 5.0.1 on 2024-01-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_orderreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
