# Generated by Django 5.0.1 on 2024-01-13 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='ordername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.order',
                                    verbose_name='Название заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество товаров в заказе'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата возврата'),
        ),
    ]
