# Generated by Django 5.0.1 on 2024-01-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='users.basket', verbose_name='Товары в заказе'),
        ),
    ]
