# Generated by Django 5.0.1 on 2024-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='delivery_address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
