# Generated by Django 5.0.4 on 2024-04-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_order_products_remove_order_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
