# Generated by Django 5.0.1 on 2024-01-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mark',
            field=models.FloatField(default=1),
        ),
    ]
