# Generated by Django 5.0.1 on 2024-01-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0005_product_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.FloatField(default=1, verbose_name='Оценка товара'),
        ),
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_category_name',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category',
                                   verbose_name='Популярная категория')),
            ],
            options={
                'verbose_name': 'Популярные категории',
                'verbose_name_plural': 'Популярная категория',
            },
        ),
    ]
