# Generated by Django 5.0.1 on 2024-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0006_alter_product_mark_popularcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularcategory',
            options={'verbose_name': 'Популярная категория', 'verbose_name_plural': 'Популярные категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
