# Generated by Django 5.0.1 on 2024-01-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0007_alter_popularcategory_options_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.SmallIntegerField(default=1, verbose_name='Оценка товара'),
        ),
    ]
