# Generated by Django 5.0.1 on 2024-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marks_count',
            field=models.IntegerField(default=0, verbose_name='Количество оценок'),
        ),
    ]
