# Generated by Django 5.0.1 on 2024-01-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0011_product_marks_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marks_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма оценок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.SmallIntegerField(default=0, verbose_name='Оценка товара'),
        ),
    ]
