# Generated by Django 5.0.1 on 2024-01-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_marks_sum_alter_product_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='categories',
            field=models.ManyToManyField(default='', to='catalog.category'),
        ),
    ]
