# Generated by Django 5.0.4 on 2024-04-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_itemtype_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название проекта')),
                ('image', models.ImageField(upload_to='project_images')),
            ],
        ),
    ]
