# Generated by Django 5.0.4 on 2024-04-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
