# Generated by Django 5.0.4 on 2024-04-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='categories',
        ),
        migrations.DeleteModel(
            name='PopularCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
