# Generated by Django 5.0.4 on 2024-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_itemtype_categories_delete_popularcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название проекта'),
        ),
    ]
